# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!

target 'ProjectTemplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 
  pod 'AFNetworking', '~> 3.1.0'
  pod 'IQKeyboardManager', '~> 5.0.4'
  pod 'TTTAttributedLabel', '~> 2.0.0'
  pod 'SDWebImage', '~> 4.2.1'
  pod 'Masonry', '~> 1.1.0'
  pod 'ReactiveObjC', '3.0.0'
  pod 'YYModel', '~> 1.0.4'
  #pod 'JSONModel', '~> 1.7.0'
  pod 'BlocksKit', '~> 2.2.5'
  pod 'MJRefresh', '~> 3.1.15'
  pod 'MSWeakTimer', '~> 1.1.0'
  pod 'AspectsV1.4.2', '~> 1.4.2'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'TAPageControl', '~> 0.2.0'
  pod 'PINCache', '~> 2.3'
  pod 'SAMKeychain', '~> 1.5.3'
  
  pod 'SGQRCode', '~> 2.2.0'
  pod 'BMKLocationKit', '~> 1.2.0'

end
